### ISSUE TITLE
Variable substitution does not work on Windows

### ISSUE THREAD

**Issue by philipp94831** [bakdata/kpops#102]
We use os.environ in order to substitute internal variables such as `pipeline_name`: https://github.com/bakdata/kpops/blob/8f5e1bdc7f4ddf13e633259908fd1d9bcc4b34e0/kpops/pipeline_generator/pipeline.py#L90. However, when calling `dict(os.environ)`, Windows returns a dictionary containing `{"PIPELINE_NAME": ...}`. Therefore, substitution does not work. We should find another way to do the substitution. In my opinion, we should not add our internal variables to os.environ but rather add os.environ to our dictionary of variables.

**Comment by sujuka99** [comment]
[Why that happens](https://github.com/python/cpython/issues/91017)

**Comment by irux** [comment]
I can take a look in to it and try to solve this. I meanly use windows , so I think this helps. Moreover I will try to take a look if everything in windows works as expected :)

**Comment by irux** [comment]
so, should I lower case it and do that quick fix? or do you propose to make big shared dict that saves all the vars ? @philipp94831

**Comment by philipp94831** [comment]
We should create our own dict
