### ISSUE TITLE
Refactor input/output types

### ISSUE THREAD

**Issue by philipp94831** [bakdata/kpops#119]
Currently, we have two types for input topics and extra output topics. However, we could use the same type but just distinguish if role is set or not because role is mandatory for extra types. The same can be applied to input pattern and output type. See https://github.com/bakdata/kpops/blob/aa44fdf6520a4ef9c520b27cfdb94e9fc35cd079/kpops/components/base_components/pipeline_component.py#L117

**Comment by sujuka99** [comment]
I would do the following:

**Output topics**

- Default type is `output`
- If role is set, type is inferred to be `extra`

This would mean that the user only needs to specify a type for `error` topics

**Input topics**

 - default type is input
 - Add an input topic type `pattern`
 - If role is set, type is inferred to be `extra-pattern` if type is `pattern`, else `extra`

I would not remove any functionality, just set some defaults and add the `pattern` type [here](https://github.com/bakdata/kpops/blob/aa44fdf6520a4ef9c520b27cfdb94e9fc35cd079/kpops/components/base_components/models/from_section.py#L6-L11)

**Comment by philipp94831** [comment]
There should be the following types for from:
- input (can be default if not specified)
- pattern

If role is specified, it is treated as extra input topics/extra input patterns

For to we need the following two types:
- output (can be default if not specified)
- error

If role is specified for the first, it is trated as extra output topics, for error it is a misconfiguration
