### ISSUE TITLE
Allow different config.yaml per environment

### ISSUE THREAD

**Issue by philipp94831** [bakdata/kpops#153]
Currently, there is only a global config.yaml. Similar to defaults and pipeline files, it would be good to allow config overrides per environment by creating files such as config_development.yaml for development specific configurations

**Comment by raminqaf** [comment]
How should we deal with the `environment` field in the config.yaml? How would that look in the different environments configs?

**Comment by philipp94831** [comment]
> How should we deal with the `environment` field in the config.yaml? How would that look in the different environments configs?

I guess it should become a cli param
