### ISSUE TITLE
Change the Helm URL to a `HttpUrl` type instead of `str`

### ISSUE THREAD

**Issue by raminqaf** [bakdata/kpops#17]
Currently, we are using strings for URLs. We can use Pydantic's `HttpUrl` type. It comes with validation out of the box. See:
https://pydantic-docs.helpmanual.io/usage/types/#urls

**Comment by Matheus920** [comment]
Hello, I'm new to opensource I want to contribute with this issue.

**Comment by philipp94831** [comment]
Hi @Matheus920, feel free to submit a PR

**Comment by raminqaf** [comment]
This will be shipped with `v3`
