### ISSUE TITLE
Allow setting syntax theme for generate step

### ISSUE THREAD

**Issue by torbsto** [bakdata/kpops#170]
[rich defaults to monokai](https://rich.readthedocs.io/en/stable/reference/syntax.html#rich.syntax.Syntax) as a syntax theme. This makes it unpleasant to read when using light color themes:

![Monokai](https://user-images.githubusercontent.com/17516685/227521144-d03b1bd2-8241-4b74-a7ad-4431d8ecf0bc.png)

The syntax theme can be modified by passing [a valid pygments theme](https://pygments.org/styles/) when creating the syntax object.

**Comment by disrupted** [comment]
I am leaning more towards using the special [ANSI themes](https://rich.readthedocs.io/en/stable/syntax.html#theme). This way the user's terminal colors are used for the syntax highlighting.

**Comment by torbsto** [comment]
But what would you choose - `ansi_light` or `ansi_dark`? I think ultimately it's the same problem. Also, it seems like it doesn't work for my setup. They both produce the same output and don't use any colors except for strings. 
![Screenshot from 2023-04-06 13-04-46](https://user-images.githubusercontent.com/17516685/230359426-0d4a2e01-d956-41ac-91d2-f14337b14110.png)

I've written a wrapper to pipe the output of `kpops generate` to `bat -l yaml`, so this issue could be closed from my side.
