### ISSUE TITLE
Add actionlint to pre-commit hooks

### ISSUE THREAD

**Issue by sujuka99** [bakdata/kpops#178]
Could [actionlint](https://github.com/rhysd/actionlint) be useful?

It would statically check our workflow files.

**Comment by sujuka99** [comment]
Can this be closed?

**Comment by disrupted** [comment]
> Can this be closed?

Yeah, since there is a dedicated CI [lint workflow](https://github.com/bakdata/kpops/blob/main/.github/workflows/lint.yaml) now, we don't need a pre-commit hook.
