### ISSUE TITLE
Use `helm repo update <repo_name>` instead of updating every repo

### ISSUE THREAD

**Issue by raminqaf** [bakdata/kpops#18]
Currently, when adding a new helm repo in the Helm wrapper, the helm repo update causes to update all Helm repositories. With Helm 3.7 one can now specify the repo name to update. Introducing this requires that every project that uses KPOps uses helm > 3.7, which is not the case right now.

**Comment by disrupted** [comment]
we should add a condition that checks if the installed version of Helm is > 3.7 to use this new approach, otherwise use the existing way of updating all helm repos.
