### ISSUE TITLE
Generate schema for `defaults.yaml`

### ISSUE THREAD

**Issue by sujuka99** [bakdata/kpops#180]
Add schema generation for `defaults.yaml` to[ `kpops schema`](https://github.com/bakdata/kpops/commit/55e8feefbe80ae9164fcc8878690a7988d0b09ca#diff-09a80e1135dee4529367636bc470e2f6c54a4d2e23fe19b39052e616b848da6cR197)

PROBLEM: Key-based union schema generation is not currently supported by Pydantic. [See here](https://github.com/pydantic/pydantic/discussions/4180)

**Comment by disrupted** [comment]
depends on #341
