### ISSUE TITLE
Provide components module as a path

### ISSUE THREAD

**Issue by sujuka99** [bakdata/kpops#187]
Currently, providing a custom components module is not documented well.
Since it is not done with a path, it is not intuitive, at least for some.

Does the current syntax follow a certain convention?
Is it possible to change the argument to `Path`? It could be translated into a string in the `Registry` class via a private method.

The alternative would be to clearly document how to provide the custom module and include an example.

**Comment by raminqaf** [comment]
Closing this because the component module should stay as a module and not a path. This should be documented in a better way.
