### ISSUE TITLE
Add support for `.env` files

### ISSUE THREAD

**Issue by raminqaf** [bakdata/kpops#20]
According to the [Pydantic documentation](https://docs.pydantic.dev/usage/settings/#dotenv-env-support), the `.env` support should come out of the box. But for some reason, this is not working.
A workaround would be to use another tool like [direnv](https://github.com/direnv/direnv).

**Comment by sujuka99** [comment]
Partial support is added in #347. All `KpopsConfig` settings are now covered.

**Comment by sujuka99** [comment]
We have decided not to add `.env` support for CLI variables due to their ever-changing nature.
