### ISSUE TITLE
KafkaConnectorConfig.name should be optional

### ISSUE THREAD

**Issue by sujuka99** [bakdata/kpops#412]
We [require](https://github.com/bakdata/kpops/blob/v3/kpops/component_handlers/kafka_connect/model.py#L29-L33) the user to set the name in KafkaConnectorConfig, but it's then [overwritten](https://github.com/bakdata/kpops/blob/v3/kpops/components/base_components/kafka_connector.py#L76-L91). The validator seems to accept that KafkaConnectorConfig.name could be None, so we should just make `KafkaConnectorConfig.name` optional.

**Comment by disrupted** [comment]
I believe that's not a good idea, `name` is a required attribute for Kafka Connector config. We just added the convenience for KPOps users not having to define it in their YAMLs, we take care of it automatically. If you're instantiating the class directly however, language tools will show an error for the missing attribute.
