### ISSUE TITLE
Test PyPi releases have wrong version number

### ISSUE THREAD

**Issue by philipp94831** [bakdata/kpops#43]
Although version was 0.4.0, the Test PyPi release was 0.5.0.dev20221222104254. However, I would expect version number to be 0.4.1.dev20221222104254

**Comment by philipp94831** [comment]
Is this related to the problem? https://github.com/bakdata/kpops/actions/runs/3758106620/jobs/6386079736 @raminqaf

**Comment by raminqaf** [comment]
No, we always do a `minor` bump and release to test PyPI. Take a look at this:
https://github.com/bakdata/kpops/blob/main/.github/workflows/publish-dev.yaml#L20-L25

**Comment by philipp94831** [comment]
But minor does not make sense. It should be patch
