### ISSUE TITLE
Release workflow should only push to GitHub pages once

### ISSUE THREAD

**Issue by yannick-roeder** [bakdata/kpops#45]
Currently the release workflow pushes 2 commits to the `gh-pages` branch which results in 2 pipelines for publishing the page. All changes should be combined into a single commit to avoid failing pipelines.

Example Commits:
- https://github.com/bakdata/kpops/commit/2627e5b1f4a6a733b6fb701e4668c45791b574f4
- https://github.com/bakdata/kpops/commit/6293926c0afa97a0704bd2ca1d50cbf846186968

**Comment by torbsto** [comment]
Do you want to a single *push* or a *commit*? The latter might be a bit tricky with mike. I guess you would have to manually squash both commits and then push with `git push origin gh-pages`.
The former can be done by simply removing the `--push` option [here](https://github.com/bakdata/kpops/blob/d3a91298299a3373be0f6ab7d8d652a92e305804/.github/actions/update-docs/action.yml#L47)

**Comment by yannick-roeder** [comment]
If pushing both commits in a single push only trigger 1 pipeline run, then I'm fine with a single push
