### ISSUE TITLE
Generate API documentation using `mkdocstrings`

### ISSUE THREAD

**Issue by raminqaf** [bakdata/kpops#492]
Use https://github.com/mkdocstrings/mkdocstrings to create docs for the new's KPOps Python API

**Comment by disrupted** [comment]
as a baseline for the first iteration I'd say we should include
- kpops API
- Pipeline API

**Comment by disrupted** [comment]
had a quick play with it (mainly for L&L) https://github.com/bakdata/kpops/tree/docs/mkdocstrings
