### ISSUE TITLE
Manifest Kubernetes resources for each KPOps command

### ISSUE THREAD

**Issue by raminqaf** [bakdata/kpops#536]
The `manifest` command only manifests the Kubernetes resource for deploying the Producer/Streams apps. Now KPOps will follow the logic bellow for each configure "operation mode"

<img width="728" alt="image" src="https://github.com/user-attachments/assets/cb8e9cae-9ce6-440d-923a-ed7b6d6d8e2c">

**Comment by disrupted** [comment]
Depends on #539
