### ISSUE TITLE
Camel case all the component, config, and default variables

### ISSUE THREAD

**Issue by raminqaf** [bakdata/kpops#66]
Currently, some of the variables like the `TopicSpec` are not camel-cased when we write the `pipeline.yaml` file:
```python
class TopicSpec(BaseModel):
    topic_name: str
    partitions_count: int | None
    replication_factor: int | None
    configs: list[dict[str, str]] | None

    class ModelConfigs(BaseConfig):
        extra = Extra.forbid
```
Also, the fields in the [PipelineConfig](https://github.com/bakdata/kpops/blob/main/kpops/cli/pipeline_config.py) class are not camel-cased. We should identify all these variables and standardize them.

**Comment by disrupted** [comment]
since this is a Python project, we should consider using snake case for everything instead of camel case. hot take but imo it's also easier to read

**Comment by disrupted** [comment]
yeah, I believe we're already consistent with snake_case. In addition, some models allow for camelCase aliases for easier copy-paste workflows. IMO this can be closed.

**Comment by raminqaf** [comment]
Closing this ticket
