### ISSUE TITLE
Create Change Log when releasing a new version

### ISSUE THREAD

**Issue by raminqaf** [bakdata/kpops#80]
We need a change log of the changes whenever we release

**Comment by raminqaf** [comment]
The changelog ci template repository has a [WIP PR](https://github.com/bakdata/ci-templates/pull/84). Once that one is merged, we can use it to generate proper changelogs.

**Comment by sujuka99** [comment]
Should we set a naming convention for PRs, issues and perhaps commit messages?

The [changelog is automatically generated](heinrichreimer/github-changelog-generator-action@v2.2), so I imagine it would be wise to be as consistent as possible with names.

**Comment by sujuka99** [comment]
Use [release-changelog-builder-action](https://github.com/mikepenz/release-changelog-builder-action)

**Comment by raminqaf** [comment]
@sujuka99 What is the current status of this issue?
It would be nice to test the new changelog action here.
https://github.com/bakdata/ci-templates/tree/main/actions/changelog-generate

**Comment by sujuka99** [comment]
There is [this](https://github.com/bakdata/kpops/tree/docs/changelog) branch which seems to only be behind as I worked on it for a bit before finding the problems with the old action. I could work on it after I finish the substitution PR. Will coordinate with @irux as he assigned himself already.

**Comment by disrupted** [comment]
changelog generation now live and working
