### ISSUE TITLE
Release and publish workflows should be separated from each other

### ISSUE THREAD

**Issue by raminqaf** [bakdata/kpops#85]
Currently, the [release.yaml](https://github.com/bakdata/kpops/blob/main/.github/workflows/release.yaml) file publishes the Python packages to PyPi **and then** creates a git tag, GitHub release, and updates/pushes the docs.
We should change the order and separate the release.yaml into to workflows: release, publish.

## Release Wrokflow
This workflow should be triggered manually, and it is similar to the current [release.yaml](https://github.com/bakdata/kpops/blob/main/.github/workflows/release.yaml) workflow. Except it only creates a git tag and creates a GitHub release

## Publish Workflow
This workflow will be **triggered only if a new tag is pushed**. This workflow will publish the Python packages to PyPi and update/pubish the docs to GitHub pages.

**Comment by MichaelKora** [comment]
@disrupted  @raminqaf 
We have a similar pending issue in the ci-templates repo: https://github.com/bakdata/ci-templates/issues/71
this will make sense for other python project as well.
So this issue should wait for reusable workflows to be created.
